### ISSUE TITLE
'cfg_files' error

### ISSUE THREAD

**Issue by Allexxann** [spm/spm#12]
When initialising SPM, MATLAB throws this:

Initialising batch system... Failed to load E:\Workspace\Toolbox\matlabbatch\cfg_mlbatch_appcfg.m
Error using cfg_files
The class 'cfg_files' is used in its own class definition as a base class, property value, or attribute value.  This is not allowed.
In file "E:\Workspace\Toolbox\spm12\matlabbatch\cfg_util.m" (v7345), function "local_initapps" at line 1478.
In file "E:\Workspace\Toolbox\spm12\matlabbatch\cfg_util.m" (v7345), function "cfg_util" at line 743.
In file "E:\Workspace\Toolbox\spm12\spm_jobman.m" (v7744), function "spm_jobman" at line 189.
In file "E:\Workspace\Toolbox\spm12\spm_jobman.m" (v7744), function "spm_jobman" at line 108.

First initialisation is usually successfull, but when I have to restart SPM, it throws an error after an error, all about cfg_something, and I have to restart MATLAB.
Not a major deal, I only have to restart while experimenting with various stuff for my scripts, and running the debugged ones does not have this issue, but it's very annoying.

Win10 x64
MATLAB 2021a
SPM 7771 (latest release)

I think this might be related: https://www.mathworks.com/help/simulink/ug/how-working-with-matlab-classes-is-different-for-code-generation.html

**Comment by VolkmarGlauche** [comment]
Hi Allexxann,

you seem to have matlabbatch installed in two locations:

E:\Workspace\Toolbox\matlabbatch

and

E:\Workspace\Toolbox\spm12\matlabbatch

Having two copies of matlabbatch in you MATLAB path at the same time will most likely result in such and other errors. Can you please check that there is only one copy of matlabbatch added to your path? If you want to use the copy outside spm12, you should add it to your path prior to starting SPM for the first time. If there is a copy of matlabbatch in the path while starting SPM, SPM will use that existing installation. Otherwise, SPM will use its bundled copy, and adding another matlabbatch to the path afterwards will break things.

Best,
Volkmar

Am Dienstag, dem 26.09.2023 um 01:41 -0700 schrieb Allexxann:

When initialising SPM, MATLAB throws this:

Initialising batch system... Failed to load E:\Workspace\Toolbox\matlabbatch\cfg_mlbatch_appcfg.m
Error using cfg_files
The class 'cfg_files' is used in its own class definition as a base class, property value, or attribute value. This is not allowed.
In file "E:\Workspace\Toolbox\spm12\matlabbatch\cfg_util.m" (v7345), function "local_initapps" at line 1478.
In file "E:\Workspace\Toolbox\spm12\matlabbatch\cfg_util.m" (v7345), function "cfg_util" at line 743.
In file "E:\Workspace\Toolbox\spm12\spm_jobman.m" (v7744), function "spm_jobman" at line 189.
In file "E:\Workspace\Toolbox\spm12\spm_jobman.m" (v7744), function "spm_jobman" at line 108.

First initialisation is usually successfull, but when I have to restart SPM, it throws an error after an error, all about cfg_something, and I have to restart MATLAB.
Not a major deal, I only have to restart while experimenting with various stuff for my scripts, and running the debugged ones does not have this issue, but it's very annoying.

Win10 x64
MATLAB 2021a
SPM 7771 (latest release)

I think this might be related: https://www.mathworks.com/help/simulink/ug/how-working-with-matlab-classes-is-different-for-code-generation.html

**Comment by Allexxann** [comment]
Oh, completely forgot about that copy.
Yes, I deleted it, and the error disappeared.
