### ISSUE TITLE
spm('ver') handling in the future

### ISSUE THREAD

**Issue by georgeoneill** [spm/spm#20]
As predicted in [this commit](https://github.com/spm/spm/commit/8d1c361b03d603033401a3fb24ac67bb4c115fc4) removing the version number from the Contents.m means the command `spm('ver')` returns just `SPM`, which in turn will break 3rd party support.

Ironically this means in the development version it breaks FieldTrip, which in turn breaks some SPM functionality. 

I've noticed that this breaks how [FieldTrip determines which version of SPM is on the path](https://github.com/spm/spm/blob/5425c610522add5d3801f4fc1139497a1cc6c441/external/fieldtrip/utilities/ft_hastoolbox.m#L701) as Contents.m no longer (for the dev version at least) returns a version number. There's elements of DAiSS which rely on FT being able to determine which version of SPM is present to run - for example, [using FT to interpoalate NIFTI images for exporting](https://github.com/spm/spm/blob/5425c610522add5d3801f4fc1139497a1cc6c441/toolbox/DAiSS/bf_write_nifti.m#L152). 

So two things we need to resolve.

1) Shall we raise an issue in FT to handle the dev (i.e versionless) version.
2) What's the plan for versioning going forward, so we dont have to implement another patch when we start considering calendar releases?

**Comment by tierneytim** [comment]
Thanks for raising this @georgeoneill. When calendar versioning is rolled out there will still be 'dev' releases of SPM. As such an issue in FT should probably be raised. However, I will raise at the SPM-dev meeting

**Comment by tierneytim** [comment]
Thanks for this @georgeoneill. There is still no firm timeline on calendar versioning rollout. In the meantime I have patched DAISS to call SPM code directly for reading MRIs instead of calling the SPM code via ft_read_mri. This avoids the need to check SPM versions via fieldtrip. As far as I can tell ft_read_mri is not called elsewhere. Hopefully this fixes your issue. If you find any other instances of this problem please report again

**Comment by georgeoneill** [comment]
Thanks @tierneytim.
