### ISSUE TITLE
spm_jsonread: parsing incorrect json file

### ISSUE THREAD

**Issue by nbeliy** [spm/spm#7]
Hi, 

In the current implementation, `spm_jsonread` do not report syntax errors in the json file that he attempt to read. For example, if input json is (no comma between second and third lines):
```json
{
  "aa": "1",
  "bb": "2"
  "cc": "3"
}
```

`spm_jsonread` parses as:
```
  struct with fields:

    aa: '1'
    bb: '2'
```

The line `cc` is ignored without any error/or warning, which can lead to the difficult to track errors downstream.

Can spm report the error?

**Comment by gllmflndn** [comment]
Hello @nbeliy 

This is indeed unexpected. I tried again after compiling the C library we use ([jsmn](https://github.com/zserge/jsmn)) in strict mode (`JSMN_STRICT`) but it didn't make a difference. It appears to be an [already reported bug upstream](https://github.com/zserge/jsmn/issues/217).

This SPM function was introduced when MATLAB and Octave didn't have JSON support but this has now changed with `jsondecode` available in R2016b and 7 respectively. This means we could replace `spm_jsonread()` with a call to `jsondecode(fileread())`. `jsondecode` doesn't allow extra options to modify the behaviour of `matlab.lang.makeValidName` as `json_jsonread` does but I presume you are not using this functionality?

If the issue is not fixed upstream, we could add a call to `jsondecode` in `spm_jsonread` instead of the current error so that if the MEX file is not present, the native implementation would be used. Would that help?

**Comment by nbeliy** [comment]
jsmn project seems to be abandoned. I doubt it would be fixed soon. But I guess can be forked and fixed somehow...

jsondecode (for me best option -- as provided by system) is matlab version dependent.

[Here](https://www.json.org/json-en.html) there some alternatives to jsmn, maybe there a better one?

**Comment by nbeliy** [comment]
> Doesn't the issue only affect manually edited JSON files? An alternative would be to rely on the [bids-matlab](https://github.com/bids-standard/bids-matlab/blob/master/%2Bbids/%2Butil/jsondecode.m) wrapper as it already switches between implementations.

Unless bids-matlab will become integrated into spm (which I would support), making spm relying on external package would not be good idea.

Just for context, I use json as configuration file, so yes, it's mostly hand-written.

For me `jsondecode` is still the best solution. But the compatibility is political decision, may be difficult to pass just for json.

**Comment by gllmflndn** [comment]
I mentioned bids-matlab as I thought you were already depending on it. If everything goes well, the aim would indeed be to have it embedded in SPM directly as a replacement of its predecessor, `spm_BIDS` (or have `spm_BIDS` using it internally) but JSON support would anyway be separate.

For now, I think I'm going to add a call to `jsondecode` in `spm_jsonread` so that it will be used if the MEX file is not present. If called, this would raise the bar for the minimal compatible MATLAB version but we are here in the development branch of the next SPM release and we will definitely raise that bar from R2007a to something in the ballpark of R2016 - this hasn't been decided yet.

**Comment by gllmflndn** [comment]
I modified `spm_jsonread` to use `jsondecode` if the MEX file is not compiled.

Future versions of SPM will likely rely on `bids-matlab` and `jsonencode`/`jsondecode`.
